### PR TITLE
V17

### PR DESCRIPTION
**Pull request by suranofsky**

### CODE REVIEW

**Comment by hmc4** [comment]
Hi, are you planning to update the code with WorldCat Search API version 2.0? https://developer.api.oclc.org/wcv2#/
OCLC ended support for version 1.0 this month, so the MatchMARC add-on no longer functions. Don't want to duplicate efforts if you are already working this. Thanks!

**Comment by hmc4** [comment]
More info: https://www.oclc.org/developer/support/worldcat-search-transition.en.html

**Comment by suranofsky** [comment]
Hi Heather,
Thanks for letting me know! Yes - I will try to update it.  I'm taking a
look at the new API.
thank you!
Michelle

**Comment by hmc4** [comment]
Thank you so much! It's a really great tool. :)

**Pull request merged**
